# Site settings
title: Rafael Fukuda - Mobile Developer
description: "Rafael Fukuda creates Xamarin, iOS, Android applications using Xamarin from Microsoft"

baseurl: ""
url: http://www.rafaelfukuda.com
# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 006DD9 #80B3FF
  secondary: 444444 #FD6E8A
  secondary-dark: 111111 #A2122F

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://de.linkedin.com/in/rafaelfukuda
  - title: github
    url: http://github.com/rafaelfukuda
  - title: angellist
    url: https://angel.co/rafaelfukuda

skills: [ C#, .NET, Xamarin, iOS Development, Android Development ]

# Credits content
credits: ''

# Build settings
markdown: kramdown
permalink: pretty
