# Site settings
title: Rafael Fukuda
description: "Rafael Fukuda é empreendedor e desenvolvedor full stack. Cria aplicativos de ponta a ponta para plataformas mobile e web."

baseurl: ""
url: http://www.rafaelfukuda.com
# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 006DD9 #80B3FF
  secondary: 444444 #FD6E8A
  secondary-dark: 111111 #A2122F

# Footer settings
footer:
  copyright: RF
  location: Localização
  social: Social
  credits: Skype

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: http://br.linkedin.com/in/rafaelfukuda/pt
  - title: github
    url: http://github.com/rafaelfukuda

# Postal address (add as many lines as necessary)
address:
  - line: São Paulo - SP
  - line: <i class="fa fa-map-marker"></i> Brasil

# Credits content
credits: '<i class="fa fa-skype"></i> rafael.fukuda'

# Build settings
markdown: kramdown
permalink: pretty
