# Site settings
title: Rafael Fukuda - Mobile Developer
description: "Rafael Fukuda is an experienced mobile developer. He creates amazing Xamarin, iOS, Android and Web applications."
about: I'm a brazilian mobile developer living in Berlin, Germany. I create iOS, Android and Windows Phone Apps using Xamarin.

baseurl: ""
url: http://www.rafaelfukuda.com
# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 006DD9 #80B3FF
  secondary: 444444 #FD6E8A
  secondary-dark: 111111 #A2122F

# Footer settings
footer:
  copyright: RF
  location: Location
  social: Social
  credits: Skype

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://de.linkedin.com/in/rafaelfukuda
  - title: github
    url: http://github.com/rafaelfukuda

skills: [ Xamarin, C#, iOS Development, Android Development, .NET, Windows Azure ]

# Postal address (add as many lines as necessary)
address:
  - line: Berlin
  - line: <i class="fa fa-map-marker"></i> Germany

# Credits content
credits: '<i class="fa fa-skype"></i> rafael.fukuda'

# Build settings
markdown: kramdown
permalink: pretty
